/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.awt.event.ItemEvent;

import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JPanel;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        new SwingLauncher(frame -> {
            JPanel panel = new JPanel();
            JComboBox<String> combo = new JComboBox<>(new String[] { "ABC", "DEF" });
            BoxLayout bLayout = new BoxLayout(panel, BoxLayout.Y_AXIS);
            panel.setLayout(bLayout);
            combo.addItemListener((itemEvent) -> {
                if (itemEvent.getStateChange() == ItemEvent.SELECTED) {
                    panel.add(new JComboBox<>(new Integer[] { 1, 3, 4, 5, 6 }));
                    panel.updateUI();
                }

            });
            panel.add(combo);
            frame.add(panel);
        }).launch();
    }
}
